version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: edu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "1212:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redispass123
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redispass123

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispass123
      - REDIS_DB=0
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    restart: unless-stopped

  edu-bot:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "28080:8080"
    volumes:
      - ./etc/config_example.yml:/app/config.yml:ro
    environment:
      CONFIG_PATH: /app/config.yml
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: redispass123
    restart: unless-stopped

volumes:
  pgdata:
  redisdata: