psql:
  user: ""
  pass: ""
  host: ""
  port: ""
  dbname: ""
  sslmode: ""
  maxIdleCons: 50
  maxOpenCons: 50
  migration: ""
  migrationApply: true
  connectTimeout: 3s
  blacklist:
    - test
    - gopg_migrations
    - schema_migrations
    - goose_db_version

token: ""