CREATE TABLE users
(
    tg_user_id BIGINT UNIQUE PRIMARY KEY NOT NULL DEFAULT 0,
    chat_id    BIGINT UNIQUE             NOT NULL DEFAULT 0,
    first_name TEXT                      NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE questions
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question   TEXT                     NOT NULL DEFAULT '',
    tag        TEXT                     NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE answers
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT REFERENCES questions (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL DEFAULT 0,
    answer      TEXT                                                                 NOT NULL DEFAULT '',
    is_correct  BOOLEAN                                                              NOT NULL DEFAULT false,
    created_at  TIMESTAMP WITH TIME ZONE                                             NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP WITH TIME ZONE                                             NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE users_questions
(
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id    BIGINT REFERENCES questions (id) ON DELETE CASCADE ON UPDATE CASCADE     NOT NULL DEFAULT 0,
    user_id        BIGINT REFERENCES users (tg_user_id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL DEFAULT 0,
    total_correct  BIGINT                                                                   NOT NULL DEFAULT 0,
    total_wrong    BIGINT                                                                   NOT NULL DEFAULT 0,
    is_edu         BOOLEAN                                                                  NOT NULL DEFAULT true,
    poll_id        TEXT UNIQUE,
    time_repeat    TIMESTAMP WITH TIME ZONE                                                 NOT NULL DEFAULT now(),
    total_serial   BIGINT                                                                   NOT NULL DEFAULT 0,
    correct_answer BIGINT,
    is_pause       BOOLEAN                                                                  NOT NULL DEFAULT false,
    created_at     TIMESTAMP WITH TIME ZONE                                                 NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP WITH TIME ZONE                                                 NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMP WITH TIME ZONE NULL
);
