CREATE TABLE IF NOT EXISTS tags
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tag        TEXT                     NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

INSERT INTO tags (tag, created_at, updated_at)
SELECT DISTINCT
    q.tag,
    now() AS created_at,
    now() AS updated_at
FROM
    questions q
WHERE
    q.tag <> '' AND NOT EXISTS (
    SELECT 1 FROM tags t
    WHERE t.tag = q.tag
);

ALTER TABLE questions ADD COLUMN tag_id BIGINT;

UPDATE questions q
SET tag_id = t.id
FROM tags t
WHERE q.tag = t.tag AND q.deleted_at IS NULL;

ALTER TABLE questions DROP COLUMN tag;

ALTER TABLE questions
    ADD CONSTRAINT fk_questions_tag
        FOREIGN KEY (tag_id) REFERENCES tags(id);
