// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package edu

var TableNames = struct {
	Answers        string
	Questions      string
	Tags           string
	Users          string
	UsersQuestions string
}{
	Answers:        "answers",
	Questions:      "questions",
	Tags:           "tags",
	Users:          "users",
	UsersQuestions: "users_questions",
}
