// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package edu

var TableNames = struct {
	Answers          string
	Questions        string
	SchemaMigrations string
	Tags             string
	Users            string
	UsersQuestions   string
}{
	Answers:          "answers",
	Questions:        "questions",
	SchemaMigrations: "schema_migrations",
	Tags:             "tags",
	Users:            "users",
	UsersQuestions:   "users_questions",
}
