// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package edu

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Answers", testAnswersUpsert)

	t.Run("Questions", testQuestionsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("UsersQuestions", testUsersQuestionsUpsert)
}
